version: '3'

#networks:
#  batman:
#    driver: bridge

services:
  db:
    image: 'mysql'
    volumes:
      - db_data:/var/lib/mysql
#    networks:
#      - batman
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: 'wordpress'
    # This will expose the port 80 of the container to an ephemeral unallocated port on the host machine.
    expose:
      - "80"
    restart: always
#    networks:
#      - batman
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  nginx:
    depends_on:
      - wordpress
    image: 'nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"

volumes:
  db_data: {}
